# comment format
[Update]
Update="Update.txt | ../Update.txt | ../../Update.txt"

[Main]
jobfile = "jobs.txt"
logfile="log.csv"
ctc2017 = [../AJ2017.csv]
spaceEfficiency=1
sourcedir = [/gpfs01/home/luhengjia/zyf/sdrscc.yuv/]
order = [1]

encoderRuns = [1]
decoderRuns = [10]

enableFrameRdOutput = [false]
enableMemUpdate = [true]

enableParcatDecOutput = [false]
[Global]
qps=[22 27 32 37]
segmentLength=64

QPIncrementFrame = [-1 -1 -1 -1]
[Cmds]
encoder = [/gpfs01/home/luhengjia/zyf_HHI/test_europe_5x/test/benchmark/EncoderApp (cfg) -c cfg/per-sequence/(name).cfg -i (file) (skip) (frames) (ip) -q (qp) (qpif) -b (name)_(qp)(seg).bin -o /dev/null --PrintHexPSNR=1 --SEIDecodedPictureHash=1 > (name)_(qp)(seg).log]
decoder = [/gpfs01/home/luhengjia/zyf_HHI/test_europe_5x/test/benchmark/DecoderApp -b (name)_(qp)(seg).bin >> (name)_(qp)(seg).log]
parcat = [/gpfs01/home/luhengjia/zyf_HHI/test_europe_5x/test/benchmark/parcat]

#for RA test, segmentLength must be "times of IntraPeriod", this IntraPeriod is defined in Table 2 of JVET-AF2017
# [Tango2]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classA_randomaccess.cfg"
# segLen=64
# mem = 12988764


# [FoodMarket4]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classA_randomaccess.cfg"
# segLen=64
# mem = 12952440


# [Campfire]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classA_randomaccess.cfg"
# segLen=32
# mem = 12943572


# [CatRobot]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classA_randomaccess.cfg"
# segLen=64
# mem = 12844932


# [DaylightRoad2]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classA_randomaccess.cfg"
# segLen=64
# mem = 13062208


# [ParkRunning3]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classA_randomaccess.cfg"
# segLen=64
# mem = 13174408


#Class B ------------------------------------------------------------------------------------------------------
# [MarketPlace]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classB_randomaccess.cfg"
# segLen=64
# mem = 4766068


# [RitualDance]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classB_randomaccess.cfg"
# segLen=64
# mem = 4753420


# [Cactus]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classB_randomaccess.cfg"
# segLen=64
# mem = 4777104


# [BasketballDrive]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classB_randomaccess.cfg"
# segLen=64
# mem = 4771148


# [BQTerrace]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classB_randomaccess.cfg"
# segLen=64
# mem = 4786652


#Class C ------------------------------------------------------------------------------------------------------
[BasketballDrill]
cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classC_randomaccess.cfg"
segLen=64
mem = 1591840


[BQMall]
cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classC_randomaccess.cfg"
segLen=64
mem = 1590196


[PartyScene]
cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classC_randomaccess.cfg"
segLen=64
mem = 1604764


[RaceHorsesC]
cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classC_randomaccess.cfg"
segLen=32
mem = 1585728

#Class F ------------------------------------------------------------------------------------------------------
# [BasketballDrillText]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classF.cfg"
# segLen=64
# mem = 1779620


# [ArenaOfValor]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classF.cfg"
# segLen=64
# mem = 4894664


# [SlideEditing]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classF.cfg"
# segLen=64
# mem = 3473840


# [SlideShow]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classF.cfg"
# segLen=64
# mem = 3418340


# Class TGM ------------------------------------------------------------------------------------------------------
# [FlyingGraphics_420]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classF.cfg"
# segLen=64
# mem = 6425568


# [Desktop_420]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classF.cfg"
# segLen=64
# mem = 6351240


# [Console_420]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classF.cfg"
# segLen=64
# mem = 6252324


# [ChineseEditing_420]
# cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classF.cfg"
# segLen=64
# mem = 6668092



#Class D ------------------------------------------------------------------------------------------------------
[BasketballPass]
cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classD_randomaccess.cfg"
segLen=64
mem = 1028160


[BQSquare]
cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classD_randomaccess.cfg"
segLen=64
mem = 1033804


[BlowingBubbles]
cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classD_randomaccess.cfg"
segLen=64
mem = 1029204


[RaceHorses]
cfg="-c cfg/encoder_randomaccess_nx2High.cfg -c cfg/per-class/classD_randomaccess.cfg"
segLen=32
mem = 1029540
