# comment format
[Update]
Update="Update.txt | ../Update.txt | ../../Update.txt"

[Main]
jobfile = "jobs.txt"
logfile = [log.csv]
ctc2017 = [../AJ2017.csv]
spaceEfficiency=1
sourcedir = [/gpfs01/home/luhengjia/zyf/sdrscc.yuv/]
order = [1]

encoderRuns = [1]
decoderRuns = [10]

enableFrameRdOutput = [false]
enableMemUpdate = [true]
enableParcatDecOutput = [false]

[Global]
qps=[22 27 32 37]
segmentLength=10000000
QPIncrementFrame=[-1 -1 -1 -1] # must have the same number with qps, and >=0 to be effective

[Cmds]
encoder = [/gpfs01/home/luhengjia/zyf_HHI/test_europe_5x/test/benchmark/EncoderApp (cfg) -c cfg/per-sequence/(name).cfg -i (file) (skip) (frames) (ip) -q (qp) (qpif) -b (name)_(qp)(seg).bin -o /dev/null --PrintHexPSNR=1 --SEIDecodedPictureHash=1 > (name)_(qp)(seg).log]
decoder = [/gpfs01/home/luhengjia/zyf_HHI/test_europe_5x/test/benchmark/DecoderApp -b (name)_(qp)(seg).bin >> (name)_(qp)(seg).log]
parcat = [/gpfs01/home/luhengjia/zyf_HHI/test_europe_5x/test/benchmark/parcat]

#Class A ------------------------------------------------------------------------------------------------------
#Class B ------------------------------------------------------------------------------------------------------
 [MarketPlace]
 cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classB_lowdelay.cfg"
 framecount=300
 mem = 3366076


 [RitualDance]
 cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classB_lowdelay.cfg"
 framecount=300
 mem = 3198052

 [Cactus]
 cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classB_lowdelay.cfg"
 framecount=250
 mem = 3196828

 [BasketballDrive]
 cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classB_lowdelay.cfg"
 framecount=250
 mem = 3325232

 [BQTerrace]
 cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classB_lowdelay.cfg"
 framecount=300
 mem = 3382732

#Class C------------------------------------------------------------------------------------------------------
[BasketballDrill]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=250
#framecount=500
mem = 1262828

[BQMall]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=300
#framecount=600
mem = 1265372

[PartyScene]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=250
#framecount=500
mem = 1273148

[RaceHorsesC]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=150
#framecount=300
mem = 1258936

# Class E------------------------------------------------------------------------------------------------------
[FourPeople]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=300
#framecount=600
mem = 1834400

[Johnny]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=300
#framecount=600
mem = 1816868

[KristenAndSara]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=300
#framecount=600
mem = 1823828

#Class F------------------------------------------------------------------------------------------------------
# [BasketballDrillText]
# cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classF.cfg -c cfg/per-class/classF_lowdelay.cfg"
# framecount=250
# mem = 1286292

# [ArenaOfValor]
# cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classF.cfg -c cfg/per-class/classF_lowdelay.cfg"
# framecount=300
# mem = 3207192

# [SlideEditing]
# cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classF.cfg -c cfg/per-class/classF_lowdelay.cfg"
# framecount=150
# mem = 2852660

# [SlideShow]
# cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classF.cfg -c cfg/per-class/classF_lowdelay.cfg"
# framecount=100
# mem = 2641956

# Class TGM------------------------------------------------------------------------------------------------------
# [FlyingGraphics_420]
# cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classF.cfg -c cfg/per-class/classF_lowdelay.cfg"
# framecount=300
# mem = 4782564

# [Desktop_420]
# cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classF.cfg -c cfg/per-class/classF_lowdelay.cfg"
# framecount=300
# mem = 4736524

# [Console_420]
# cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classF.cfg -c cfg/per-class/classF_lowdelay.cfg"
# framecount=300
# mem = 4616368

# [ChineseEditing_420]
# cfg="-c cfg/encoder_lowdelay_nx2High.cfg -c cfg/per-class/classF.cfg -c cfg/per-class/classF_lowdelay.cfg"
# framecount=300
# mem = 4889984


#Class D------------------------------------------------------------------------------------------------------
[BasketballPass]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=250
mem = 896000

[BQSquare]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=300
mem = 907424

[BlowingBubbles]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=250
mem = 897048

[RaceHorses]
cfg="-c cfg/encoder_lowdelay_nx2High.cfg"
framecount=150
mem = 903344
